### ISSUE TITLE
init-présentation

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-crud-laravel-standard#20]
## Travail à faire
- Élaboration d'un presentation sans contenu avec les pages et leurs titres

## Livrable

- README-app/*
- docs/* : j'ai modifier tous les fichier dans cette repertoire

- readme.md : ajouter le lien de presentation

- readme.json : ajouter le lien de presentation

**Comment by husseinbouik** [comment]
- la description de la tâche n'est pas valide

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue
